### ISSUE TITLE
Experimental UI - Console errors for Authors

### ISSUE THREAD

**Issue by apphutdev** [ugo-quaisse/sitecore-author-toolbox#34]
**Describe the bug**
Sitecore Authors are unable to load elements of Experimental UI. Works fine for Admins but Authors do not see the save bar and much of the skin/theme is still showing as classic Sitecore UI.

**To Reproduce**
1. Login as Authour
2. Enable Sitecore Author Chrome Plugin
3. Toggle on all options
4. See error in Console

Content%20Editor.aspx:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'includes')
at insertSavebar (chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/modules/experimentalui.js:117:68)
at sitecoreAuthorToolbox (chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/modules/contenteditor.js:60:5)
at resumeFromWhereYouLeftOff (chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/modules/history.js:74:7)
at chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/toolbox.min.js:1:2700

**Expected behavior**
The UI switches to show new skin with save bar in the top right corner

**Comment by ugo-quaisse** [comment]
Hello this is fixed with 7.1.2
Thanks
